name: Test Nginx Action
on: [push]

jobs:
	test_nginx:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v3
			- uses: Girish/nginx-docker-action@v1
				id: nginx
			- run: echo "Nginx status: ${{ steps.nginx.outputs.nginx_status }}"
